# cases_path   <- "../csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"
cases_path   <- "../csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
pop_path     <- "data/pop_data.csv"
recover_path <- "../csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"
# death_path   <- "../csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"
death_path   <- "../csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
demo_path    <- "../wirvsvirus/demographics.csv"