---
title: ''
output: html_document
---
The Danish State Serum Institute (SSI) are at the time of writing (March 20, 2020) publishing daily reports on the development of COVID-19 in Denmark. [The full reports can be found here](https://www.ssi.dk/aktuelt/sygdomsudbrud/coronavirus/covid-19-i-danmark-epidemiologisk-overvaagningsrapport). Included in these reports are, amongst other things, daily data on the number of tested people in Denmark as well as the number of confirmed positive tests. Furthermore, SSI provides cumulative data on the age distribution among the tested people. On this page you can visualise these data.

Usage note 1: SSI only reports the daily number of test for the last 14 days and aggregate everything before that. When viewing daily data, we thus only show the past 14 days.

Usage note 2: When viewing cumulative data, be aware that the Danish testing protocol [was changed](https://www.ssi.dk/aktuelt/nyhedsbreve/epi-nyt/2020/uge-12---2020) on the $12^\text{th}$ of March. After this date, only patients with severe symptoms are tested. In comparison, before this date, there was a large effort made to test everyone returning from trips to primarily Austria and Italy. Generally, these people were often infected, leading to an unnaturally high positive test rate. Thus, when viewing cumulative data, the overall trend in the percentage of positive tests appears to be decreasing, even though the overall daily percentage of positive tests is actually increasing.